version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    # To have a reference to local file system
    volumes:
      - /app/node_modules
      - ./server:/app      
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  rtmpserver:
    build:
      dockerfile: Dockerfile.dev
      context: ./rtmpserver
    volumes:
      - /app/node_modules
      - ./rtmpserver:/app