apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: jeffreyzhu/streams-application-server
          ports:
            - containerPort: 8000
          # Environment variables
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
              # Secret object: Securely stores a piece of information
              #                in the cluster, such as a database 
              #                password.
              #         
              # Run an imperative command in the terminal to create
              # secret for us. The following is the command:
              #           
              # kubectl create secret generic <secret-name> 
              # --from-literal key=value           
            - name: PGPASSWORD
              # This property says to get the value for this 
              # environment variable from some configuration.
              valueFrom:
                secretKeyRef:
                  # <secret-name> from the kubectl command
                  name: pgpassword
                  # key from the kubectl command
                  key: PGPASSWORD