export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const GET_PROFILE = 'GET_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const GET_DB_PROFILE = 'GET_DB_PROFILE';
export const SET_DB_PROFILE = 'SET_DB_PROFILE';
export const REMOVE_DB_PROFILE = 'REMOVE_DB_PROFILE';

export const CREATE_STREAM = 'CREATE_STREAM';
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
export const CLEAR_CURRENT_STREAM = 'CLEAR_CURRENT_STREAM';

export const CLEAR_FORM = 'CLEAR_FORM';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
